services:
  web:
    build:
      context: .
      dockerfile: ./DockerFiles/web.dockerfile
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - ecommerce_network

  
  app:
    build: 
      context: ../
      dockerfile: ./ecommerce/DockerFiles/app.dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - ecommerce_network


  db:
    build:
      context: .
      dockerfile: ./DockerFiles/db.dockerfile
    environment: 
      POSTGRES_DB: ecommerceDB
      POSTGRES_PASSWORD: 0938460904am
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network
    ports:
      - "5432:5432"


volumes:
  postgres_data:


networks:
  ecommerce_network:
    driver: bridge
